language: php
php:
   - 7.1
before_script:
  - composer install --prefer-source
  - ls
  - php -S localhost:8080 -t web > /dev/null 2>&1 &
script:
  - vendor/bin/codecept run
notifications:
  email: false